config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  resources :products do
      get 'search', on: :collection
  end
  namespace :admin do
      resources :products
  end
  root :to => 'products#index'
  get 'products/:id/purchase', to: 'products#purchase', as: :purchase_product
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  validates_presence_of :picture
  def decrement_quantity
    self.quantity -= 1
  end
  def self.search(term)
    self.where("lower(name) LIKE lower(?)", "%#{term}%")
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  before_action :authenticate_admin!
  def index
    @products = Product.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  def new
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to admin_products_url, notice: 'Producto creado.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(product_params)
        format.html { redirect_to admin_products_url, notice: 'Producto actuaizado.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to admin_products_url, notice: 'Producto eliminado.'}
      format.json { head :no_content }
    end
  end

  private
  # Never trust parameters from the scary internet, only allow the white list through.
  def product_params
    params.require(:product).permit(:name, :description, :picture, :price, :quantity)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end
#   def purchase
#       @product = Product.find(params[:id])
#       if @product.quantity <= 0
#           respond_to do |format|
#           format.html { redirect_to @product, error: 'El producto no está disponible' }
#       end
#       @product.decrement_quantity
#       @product.save!
      
#       respond_to do |format|
#       format.html { redirect_to @product, notice: 'Producto comprado' }      
#   end
  def purchase
      @product = Product.find(params[:id])
      if (@product.quantity <= 0)
        #Encontrar cómo mostrar mensajes en rojo para simbolizar error <-IMPORTANTE->
        respond_to do |format|
          format.html { redirect_to @product, notice:"El producto no está disponible" }
        end
      else
         @product.decrement_quantity
         @product.save!
    
         respond_to do |format|
          format.html { redirect_to @product, notice: 'Producto comprado' }
         end 
      end
  end
  
  def search
      @product_name = params[:product_name]
      @products = Product.search(@product_name)
  end
  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :picture, :price, :quantity)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/_form.html.erb
<%= form_for [:admin, @product] do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <label>Nombre:</label><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <label>Descripción:</label><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <label>Imágen:</label><br>
    <%= f.text_field :picture %>
  </div>
  <div class="field">
    <label>Precio:</label><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <label>Cantidad:</label><br>
    <%= f.number_field :quantity %>
  </div>
  <div class="actions">
    <%= f.submit 'Guardar' %>
  </div>
<% end %>

app/views/admin/products/edit.html.erb
<h1>Editar Producto</h1>

<%= render 'form' %>

<%= link_to 'Regresar', admin_products_path %>

app/views/admin/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listado de Productos</h1>

<table>
  <thead>
    <tr>
      <th>Picture</th>
      <th>Nombre</th>
      <th>Descripción</th>
      <th>Precio</th>
      <th>Cantidad</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= image_tag product.picture, width: '50' %></td>
        <td><%= product.name %></td>
        <td><%= product.description %></td>
        <td><%= number_to_currency product.price, precision: 0 %></td>
        <td><%= product.quantity %></td>
        <td><%= link_to 'Editar', edit_admin_product_path(product) %></td>
        <td><%= link_to 'Borrar', admin_product_path(product), method: :delete,
                        data: { confirm: 'Estás seguro que deseas borrar este producto?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'Nuevo Producto', new_admin_product_path %>

app/views/admin/products/new.html.erb
<h1>Crear Producto</h1>

<%= render 'form' %>

<%= link_to 'Regresar', admin_products_path %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Tienda Rails Girls Cali', root_path, class: "navbar-brand" %>
      <%= form_tag search_products_path, class: 'navbar-form navbar-left pull-right',
             role: 'search', method: :get do %>
           <div class="form-group">
              <%= text_field_tag :product_name, @product_name, class: 'form-control',
                       placeholder: 'Buscar productos' %>
           </div>
           <%= submit_tag 'Buscar', class: 'btn btn-default' %>
      <% end %>
      <% if admin_signed_in? %>
        <ul class="nav navbar-nav navbar-right">
          <li>
            <%= link_to "Cerrar Sesión", destroy_admin_session_path, method: :delete %>
          </li>
        </ul>
     <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tienda Rails Girls Cali 2017</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
  <% if notice.present? %>
    <div id="notice" class="alert alert-success alert-dismissible">
      <%= notice %>
    </div>
  <% end %>
  <% if flash[:error] %>
  <div id="notice" class="alert alert-error alert-dismissible">
      <%= flash[:error] %>
    </div>
  <% end %>
  <div class="container-fluid">
    <%= yield %>
  </div>
</body>
</html>

app/views/products/index.html.erb
<% @products.in_groups_of(4, false).each do |products| %>
  <div class="row">

    <% products.each do |product| %>
      <div class="col-md-3">
        <div class="product-cont thumbnail">
          <h3><%= link_to product.name, product %></h3>
          <%= link_to image_tag(product.picture, width: '200'), product %>
          <p><%= number_to_currency product.price, precision: 0 %></p>
        </div>
      </div>
    <% end %>
  </div>
  <p>
    <%= link_to 'New Product', new_product_path %>
  </p>
<% end %>

app/views/products/search.html.erb
<h1><%= "Resultados de productos: #{@product_name}" %></h1>
<br>
<br>
<ul>
  <% @products.each do |product| %>
    <li>
      <h3><%= product.name %></h3>
      <%= link_to image_tag(product.picture, width: '200'), product %>
      <%= number_to_currency product.price, precision: 0 %>
      <%= link_to 'Detalle', product %></li>
  <% end %>
</ul>

<%= link_to 'Regresar a productos', products_path %>

app/views/products/show.html.erb
<div class="row product-details">
  <div class="col-md-offset-2 col-md-4 text-center">
    <h1><%= @product.name %></h1>
    <%= image_tag @product.picture, width: 300 %>
  </div>
  <div class="col-md-4 ">
    <div class="description">
      <p><%= @product.description %></p>
      <p>
        <strong>Precio:</strong>
        <%= number_to_currency @product.price, precision: 0 %>
      </p>
      <p>
        <strong>Cantidades disponibles:</strong>
        <%= @product.quantity %>
      </p>
      <h3>
        <%= link_to 'Comprar', purchase_product_path(@product),
                    class: 'btn btn-lg btn-success'%>
      </h3>
    </div>
  </div>
</div>